### ISSUE TITLE
Terminal commands don't work.

### ISSUE THREAD

**Issue by SmithJones2177** [Szumi57/LethalInternship#13]
I'm not to sure why it isn't working, but the terminal commands don't work. Whenever I try typing "Intern" to buy them, it just comes up with a error saying that there is no action supplied with the word. I also saw on a video that there is supposed to be a section for the mod.

Here are some screenshots:

![20240805145513_1](https://github.com/user-attachments/assets/82d38e5f-e916-4287-9b33-7c8d3f42deb5)

![20240805145520_1](https://github.com/user-attachments/assets/c226bdec-673d-489d-aefc-ad6f36710538)

I do have like 100 mods enabled though so it might be conflicting with one of the mods.

**Comment by Szumi57** [comment]
Hi, thanks for reporting , I can't see the lethal internship menu in the help page on your screenshot, you are maybe right, looks like an conflict with 1 (or more) mods. 
I will need your mod list (the code or a list) to debug all that.

**Comment by SmithJones2177** [comment]
> Hi, thanks for reporting , I can't see the lethal internship menu in the help page on your screenshot, you are maybe right, looks like an conflict with 1 (or more) mods. I will need your mod list (the code or a list) to debug all that.

Here's my Thunderstore modpack code: 019128b0-7a68-979d-f38d-58daa1bfbf5c

I hope this helps.

**Comment by Szumi57** [comment]
Hi, I checked your modpack, there's a conflict with Mike's tweaks. It's a pretty old mod (8 month since update), it says it targets v45, and there are errors in the patches when it is loaded... I can't fix mod of other people, I suggest to just remove this mod from your modpack, LethalIntership works with all the others mods.

**Comment by SmithJones2177** [comment]
Ok, I'll remove it. Thanks for letting me know.
