### ISSUE TITLE
Better XP Conflict

### ISSUE THREAD

**Issue by declanfruzyna** [Szumi57/LethalInternship#2]
There appears to be some conflict with Better XP on leaving a moon where you soft lock
console log at time of error
![image](https://github.com/user-attachments/assets/e63d294c-949e-4232-9297-bd6dd2eb602e)
mods used:
![image](https://github.com/user-attachments/assets/87be16f6-e027-4f33-a3e2-f4846d7726b2)

**Comment by Szumi57** [comment]
Hi, thanks for the reporting the bug ! I will look at that. :)

**Comment by Szumi57** [comment]
Hopefully fixed with new version
