### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by wczbl** [Szumi57/LethalInternship#3]
This mod is cool, however, will the price and health of the intern be customizable in the future? By the way, can you add an option that allows interns to spawn on moons as well? 

Anyways, great mod!

**Comment by Szumi57** [comment]
Hi ! 
Yes a bunch of stuff will be configurable, I will add it soon.

Sorry I don't understand your second question, what do you mean by spawn on moons ? not by dropship ?

**Comment by wczbl** [comment]
Yes, not by dropship
