### ISSUE TITLE
Interns really want to hold Maneater

### ISSUE THREAD

**Issue by ShadowWolf90** [Szumi57/LethalInternship#40]
Hi!

I'm 100% sure this is not bug, but rather little oopsie in code.
Maneater in Baby Form is pickable and interns when  they spot him they rush to him to pick him up.

**Comment by Szumi57** [comment]
Fixed in v0.17.0, config added for grabbing maneater or not

**Comment by ShadowWolf90** [comment]
Fixed, no issues found, closing!
