### ISSUE TITLE
Picking up corpse or grabbing intern

### ISSUE THREAD

**Issue by ShadowWolf90** [Szumi57/LethalInternship#41]
Picking up corpse of intern or grabbing him and dropping him causes problem.
If body weight is set to 0 or it's edited overall by any mod, picking up and dropping body causes player to have huge weight applied till death or if player picks up again corpse. Grabing intern or picking up corpse again fixes weight.

**Comment by Szumi57** [comment]
Fixed in v0.17.0

**Comment by ShadowWolf90** [comment]
Fixed, no issues found, closing!
