### ISSUE TITLE
Invisible corpse?

### ISSUE THREAD

**Issue by ShadowWolf90** [Szumi57/LethalInternship#42]
Noticed mostly on Experimentation.

Interns most of the time go next to the water tower and bring invisible corpse. 
It's really invisible if it's hold by Intern or if it's dropped and picked up by player.

I can't tell how this corpse spawns or what's the cause of it.

**Comment by Szumi57** [comment]
Hi, thanks for your reporting !
Yes I saw this bug too, I rewrite most of the things concerning grabbable interns, so this bug get fix with that too.
It's for next update :)

**Comment by ShadowWolf90** [comment]
Hi!
Thanks for responce!
I also made 2 more bug reports: #40 and #41

**Comment by Szumi57** [comment]
Fixed in v0.17.0

**Comment by ShadowWolf90** [comment]
Fixed, no issues found, closing!
