### ISSUE TITLE
Error when a friend logs in

### ISSUE THREAD

**Issue by Timofey1337png** [Szumi57/LethalInternship#52]
We downloaded only Internship, but when entering a friend lobby crashes out and the host writes.
![Intern](https://github.com/user-attachments/assets/67fdb0d4-c1ae-4e1d-9909-8c350dffc906)

**Comment by Szumi57** [comment]
Thanks for reporting, I'm on it + another one

**Comment by Szumi57** [comment]
Fix in version 0.18.3

**Comment by Timofey1337png** [comment]
Everything works, thank you!
