### ISSUE TITLE
Masked attack error 

### ISSUE THREAD

**Issue by Timofey1337png** [Szumi57/LethalInternship#54]
When attacking an intern, the masked one seems to hand him his task and freezes in an attack animation.
Tried it with the MaskedEnemyOverhaulFork mod .
![intern error](https://github.com/user-attachments/assets/2a810173-6292-4066-bf57-293112ae01ed)

**Comment by Szumi57** [comment]
Sorry I could not reproduce it on my side, can I have your modpack code ?

**Comment by Timofey1337png** [comment]
Yes.
 0192d3f1-da9c-d621-daba-c3d8e47b4c0e
