### ISSUE TITLE
(Intentional?) Interns will hopelessly run towards beehives and instantly die to circuit bees 

### ISSUE THREAD

**Issue by dopadream** [Szumi57/LethalInternship#8]
https://github.com/user-attachments/assets/d2f2f19a-50fc-4bc6-9942-97d292827583

**Comment by Szumi57** [comment]
Hi, yes the intern badly wants to grab the bees nest, but he gets scared by the bees (and not run quickly enough).
I saw this "problem" too, and I hesitate to make the interns ignore some items (bees net, dead bodies) so they die less.

I just want to add that the usefullness (or the lack of) of interns is kind of intended by the spirit of the mod. I wanted to make them not very smart and vulnerable, and replaceable...
If they die too much on this kind of thing though then yes I will make the change.

**Comment by dopadream** [comment]
Maybe at some point it would be a good idea to add an optional configurable list of items that interns ignore?

**Comment by BTFighter** [comment]
> Hi, yes the intern badly wants to grab the bees nest, but he gets scared by the bees (and not run quickly enough). I saw this "problem" too, and I hesitate to make the interns ignore some items (bees net, dead bodies) so they die less.
> 
> I just want to add that the usefullness (or the lack of) of interns is kind of intended by the spirit of the mod. I wanted to make them not very smart and vulnerable, and replaceable... If they die too much on this kind of thing though then yes I will make the change.

Maybe make them smart (as much as possible) and then allow the host to make them dumber (Configs)? Similar to [Bot Warfare](https://www.moddb.com/mods/bot-warfare) for Call of Duty games.

**Comment by dopadream** [comment]
Fixed in 0.14.7
